PRAGMA foreign_keys=OFF;
CREATE TABLE `exvoto_new` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`internal_id` text(20),
	`offering_sem_id` integer,
	`conservation_sem_id` integer,
	`province` text(50),
	`virgin_or_saint` text(100),
	`exvoto_date` text,
	`benefited_name` text(100),
	`offerer_name` text(100),
	`offerer_gender` text(10),
	`offerer_relation` text(100),
	`characters` text(200),
	`profession` text(100),
	`social_status` text(100),
	`miracle` text(50),
	`miracle_place` text(200),
	`material` text(100),
	`dimensions` text(50),
	`text_case` text(20),
	`text_form` text,
	`writing_type` text,
	`linguistic_competence` text,
	`references` text,
	`extra_info` text(500),
	`transcription` text,
	`conservation_status` text(100),
	`image` blob,
	`epoch` text(25),
	`lugar_origen` text(200),
	`updated_at` text
);
INSERT INTO `exvoto_new` (
	`id`,
	`internal_id`,
	`offering_sem_id`,
	`conservation_sem_id`,
	`province`,
	`virgin_or_saint`,
	`exvoto_date`,
	`benefited_name`,
	`offerer_name`,
	`offerer_gender`,
	`offerer_relation`,
	`characters`,
	`profession`,
	`social_status`,
	`miracle`,
	`miracle_place`,
	`material`,
	`dimensions`,
	`text_case`,
	`text_form`,
	`writing_type`,
	`linguistic_competence`,
	`references`,
	`extra_info`,
	`transcription`,
	`conservation_status`,
	`image`,
	`epoch`,
	`lugar_origen`,
	`updated_at`
) SELECT
	`id`,
	`internal_id`,
	`offering_sem_id`,
	`conservation_sem_id`,
	`province`,
	`virgin_or_saint`,
	`exvoto_date`,
	`benefited_name`,
	`offerer_name`,
	`offerer_gender`,
	`offerer_relation`,
	`characters`,
	`profession`,
	`social_status`,
	`miracle`,
	`miracle_place`,
	`material`,
	`dimensions`,
	`text_case`,
	`text_form`,
	`writing_type`,
	`linguistic_competence`,
	`references`,
	`extra_info`,
	`transcription`,
	`conservation_status`,
	`image`,
	`epoch`,
	`lugar_origen`,
	`updated_at`
FROM `exvoto`;
DROP TABLE `exvoto`;
ALTER TABLE `exvoto_new` RENAME TO `exvoto`;
PRAGMA foreign_keys=ON;
